"""Initial migration.

Revision ID: d131ba185473
Revises:
Create Date: 2025-11-30 12:21:15.736908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd131ba185473'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('compass',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('q1', sa.Text(), nullable=True),
    sa.Column('q2', sa.Text(), nullable=True),
    sa.Column('q3', sa.Text(), nullable=True),
    sa.Column('ac1', sa.Text(), nullable=True),
    sa.Column('ac2', sa.Text(), nullable=True),
    sa.Column('le1', sa.Text(), nullable=True),
    sa.Column('le2', sa.Text(), nullable=True),
    sa.Column('le3', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_membership',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_membership')
    op.drop_table('compass')
    op.drop_table('user')
    op.drop_table('team')
    # ### end Alembic commands ###
